### ISSUE TITLE
16:9 Patch

### ISSUE THREAD

**Issue by zerodoom** [CyberNomadic/GDL_Patch#1]
First off this is amazing. I'm revisiting Gauntlet with my kids and love to see some of the long-standing bugs fixed.  

My question is could you create a version of the patch that also bakes in 16:9 aspect ratio. I can use codes on PCs but running it on a Wii with a baked in widescreen patch would be awesome.

**Comment by CyberNomadic** [comment]
Thank you for the kind words! This was/is a fun passion project and I'm glad you and your kids are able to enjoy it!

https://github.com/CyberNomadic/GDL_Patch/blob/widescreen/GDL13WideScreen.xdelta

Apply this xDelta over an already 1.3 patched version of the ISO. I haven't tested it on console, so I don't know how good of an experience it will provide. Best of luck!

EDIT: It should kick in once you're on the character selection menu.

**Comment by zerodoom** [comment]
I tested it out and it works great so far on a Wii. Thanks!
