### ISSUE TITLE
Repo has no code/patches

### ISSUE THREAD

**Issue by Zabadam** [CyberNomadic/GDL_Patch#3]
The repo contains only a readme and a license. If not for releases, where is the code?

**Comment by CyberNomadic** [comment]
I do not know of a way for me to provide the assembly that I've written or edited that would make sense or be useful. The patch file modifies the .dol, banner, and a character file. The main.dol can be opened with Ghidra or IDA Pro and you can see the assembly that's been changed.

If you have any suggestions, I'd certainly be open to them.

**Comment by Zabadam** [comment]
I'm just ignorant on what actually goes into these patches, it seems. Thanks for the insight!
